# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# Public Model Configurations
# ===========================
# Copy this file to model_configs.yaml.

# -----------------------------------------------------------------------------
# DMC 6.1SB models
# -----------------------------------------------------------------------------

dmc61sbr_reglu:
  module: ._dmc61sb_model
  class: TraceableMLVC
  # Perceptual alternative:
  # weights_path: pretrained/mlvc-perceptual-v1.ckpt
  # weights_version: perceptual_v1
  weights_path: pretrained/mlvc-psnr-v1.ckpt
  weights_version: psnr_v1
  iframe_period: 64
  reset_period: null
  split_type: dmc61sbr_e1d1
  params:
    disable_feature_reset: true
    depth_conv_block_params:
      activation: LeakyReLU
      zero_init_residual: true
      chunk_mode: gated
      ffn_gate_activation: ReLU1
    feature_channels: 128
    spatial_prior_channels: 256
    input_offset: -0.5
    memory_activation: identity
    chain_feature_adaptors: true

dmc61sbr_mini_reglu:
  module: ._dmc61sb_model
  class: TraceableMLVC
  # Perceptual alternative:
  # weights_path: pretrained/mlvc-s-perceptual-v1.ckpt
  # weights_version: perceptual_v1
  weights_path: pretrained/mlvc-s-psnr-v1.ckpt
  weights_version: psnr_v1
  iframe_period: 1024
  reset_period: null
  ltr_start_idx: 8
  ltr_period: 64
  split_type: dmc61sbr_e1d1
  params:
    disable_feature_reset: true
    depth_conv_block_params:
      activation: LeakyReLU
      zero_init_residual: true
      chunk_mode: gated
      ffn_gate_activation: ReLU1
    feature_channels: 48
    spatial_prior_channels: 128
    input_offset: -0.5
    memory_activation: identity
    recon_channels: 192
    hidden_channels: 192
    hyperprior_num_blocks: 2
    y_scale_repeat: 4
    z_channels: 48
    y_channels: 48
    chain_feature_adaptors: true
    hyperprior_variant: mini
    feature_extractor_num_conv1_layers: 1
    feature_extractor_num_conv2_layers: 1
